config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users

  resources :users, only: [:show]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
  
  resources :topics do
    resources :bookmarks, except: [:index] do
      resources :likes, only: [:create, :destroy]
    end
  end

  post :incoming, to: 'incoming#create'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  #mount_uploader :bookmarkpic, BookmarkpicUploader

  default_scope { order('created_at DESC') }

  has_many :likes, dependent: :destroy

  def self.new_with_embed(url) 
    #ebedly stuff, connect, get image
    embedly_api = Embedly::API.new(key: '53d44b26a3cc4012a790e2b1d8fe2caa')
    obj = embedly_api.oembed :url => url
    if obj.first.thumbnail_url
      embed_url = (obj.first.thumbnail_url).html_safe
    else
      embed_url = asset_path("bookmark.png")
    end

    #add to amazon, get amazon_url 

    new(url: amazon_url)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics
  has_many :bookmarks
  has_many :likes, dependent: :destroy
  has_many :liked_bookmarks, through: :likes, source: :bookmark

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def show
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new(params.require(:bookmark).permit(:url))
    #@bookmark = Bookmark.new_with_embed(params.require(:bookmark).permit(:url))

    @bookmark.user = current_user
    @bookmark.topic = @topic
    authorize @bookmark
    if @bookmark.save
      flash[:notice] = "This bookmark was successfully saved."
      redirect_to [@topic, @bookmark]
    else
      flash[:error] = "There was an error saving this bookmark. Please try again."
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = "Bookmark was successfully deleted."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the bookmark. Please try again."
      render :show
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.update_attributes(params.require(:bookmark).permit(:url))
      flash[:notice] = "Bookmark was updated"
      redirect_to [@topic, @bookmark]
    else
      flash[:error] = "There was an error updating the bookmark. Please try again."
      render :new
    end

  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    # Take a look at these in your server logs
    # to get a sense of what you're dealing with.
    puts "INCOMING PARAMS HERE: #{params}"

    @user = User.find_by(email: params[:sender])
    @topic = Topic.find_or_create_by(title: params[:subject])
    @bookmark = Bookmark.new(url: params['stripped-text'])

    @bookmark.user = @user
    @bookmark.topic = @topic
    @bookmark.save
    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    authorize like

    if like.save
      flash[:notice] = "You successfully liked this bookmark!"
    else
      flash[:error] = "An error occured while trying to like this bookmark. Please try again."
    end

    redirect_to request.referer
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.find(params[:id])

    authorize like

    if like.destroy
      flash[:notice] = "You successfully unliked this bookmark"
    else
      flash[:error] = "An error occured while trying to unlike this bookmark. Please try again."
    end
    
    redirect_to request.referer
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end


  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(params.require(:topic).permit(:title))
    if @topic.save
      flash[:notice] = "Topic was saved"
      redirect_to @topic
    else
      flash[:error] = "There was an error saving the topic. Please try again."
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "Topic was deleted."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic. Please try again."
      render :show
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_bookmarks = @user.bookmarks.includes(:topic).group_by{|b| b.topic.title}
    #@user_bookmarks = @user.bookmarks.includes(:topic).reorder('topics.title ASC')
    @liked_bookmarks = current_user.liked_bookmarks
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

require 'embedly'
require 'json'

  def display(url)
    embedly_api = Embedly::API.new(key: ENV["EMBEDLY_API_KEY"])
    obj = embedly_api.oembed :url => url
    if obj.first.thumbnail_url
      (obj.first.thumbnail_url).html_safe
    else
      asset_path("bookmark.png")
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_controller_helper.rb
module IncomingControllerHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<%= form_for [@topic, @bookmark] do |f| %>
  <%= f.label :url %>
  <%= f.text_area :url, class: "form-control" %>

  <%= f.submit "Submit", class: "btn btn-success" %>
<% end %>

app/views/bookmarks/new.html.erb
<%= form_for [@topic, @bookmark] do |f| %>
  <%= f.label :url %>
  <%= f.text_area :url, class: "form-control" %>

  <%= f.submit "Save", class: "btn btn-success"  %>
<% end %>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.url %></h1>
  <%= link_to "Edit bookmark", edit_topic_bookmark_path(@topic, @bookmark), class: 'btn btn-default' %>
  <%= link_to "Delete bookmark", [@topic, @bookmark], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this bookmark?'} %>
  
<div class="col-md-12 bookmark_image">
  <%= image_tag("bookmark.png") %>
</div>

  <% if policy(Bookmark.new).create? %>
  <div class="like_bookmark">
    <%= render partial: 'likes/like', locals: { bookmark: @bookmark } %>
  </div>

  <div class="clearfix"></div> <!-- better solution? -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta name="viewport" content="width=device-width", initial-scale="1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
  </div>
<% end %>


  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocmarks", root_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <li><%= link_to "About", about_path %></li>


      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= link_to current_user.name, current_user %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>
    <%= yield %>
  </div>

</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark.topic, bookmark, like], class: 'btn btn-danger', method: :delete do %>
        <i class= "glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
      <% end %>
    <% else %>
      <%= link_to [bookmark.topic, bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; like
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>All Blocmarks</h1>

<div class="create_topic">
  <%= button_to "Create a topic", new_topic_path, method: :get, class: "btn btn-success" %>
</div>

<% @topics.each do |topic| %>
  <div class="topic_row">
    <h3><%= link_to topic.title, topic %></h3>
    <div class="row">
      <% topic.bookmarks.take(4).each do |bookmark| %>
        <div class="col-md-3">
          <div>
            <%= bookmark.url %>
          </div>
            <img src="<%= display(bookmark.url) %>" style="width:200px;"></img>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/topics/new.html.erb
<%= form_for @topic do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>

<div class="delete_topic">
  <%= link_to "Delete Topic", [@topic], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?'} %>
</div>

  <% @bookmarks.each_slice(4) do |bookmark_group| %>
<div class="row">
  <% bookmark_group.each do |bookmark| %>
    <div class="col-md-3">
      <%= link_to bookmark.url, [@topic, bookmark] %>
      <%= image_tag("bookmark.png") %>
    </div>
    <% end %>
</div>
  <% end %>
<div class="row">
    <% if policy(Bookmark.new).create? %>
    <div class="create_bookmark">
        <%= link_to "Create a bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
      </div>
        <div class="clearfix"></div> <!-- better solution? -->
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h2>My Blocmarks</h2>
<div class="profile_bookmarks">
<% @user_bookmarks.each do |bookmark_group| %>
  <div class="row">
    <h4><%= link_to bookmark_group.first %></h4>
    <div class="row">
      <% bookmark_group.last.each do |bookmark| %>
        <div class="col-md-3">
          <div>
            <%# bookmark.topic.title %><!-- use for testing -->
            <i><%= bookmark.url %></i>
          </div>
          <%= image_tag("bookmark.png") %>
          <%= link_to "Remove", topic_bookmark_path(bookmark.topic, bookmark), method: :delete, data: { confirm: 'Are you sure you want to delete this bookmark?'} %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
</div>

<div class="clearfix"></div> <!-- better solution? -->

<h2>Liked Blocmarks</h2>
<div class="row">
  <% @liked_bookmarks.each do |bookmark| %>
    <div class="col-md-3">
      <div>
        <i><%= bookmark.url %></i>
      </div>
      <%= image_tag("bookmark.png") %>
      <p>LIKE/UNLIKE</p>
      <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
    </div>
  <% end %>
</div>

app/views/welcome/about.html.erb
<h1>About Blocmarks</h1>

<p>Created by: Seth Jones</p>
<p>Email: sethjmusic@gmail.com</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocmarks!</h1>
<p>A production quality social bookmarking app that allows users to email, manage and share bookmarked URLs.</p>

<div class="row">
<div class="col-md-3">
  <%= link_to "Sign In", new_user_session_path, class: 'btn btn-success btn-lg' %> 
</div>
<div class="col-md-3">
  <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-lg' %>
</div>
</div>